### ISSUE TITLE
Multiple Services

### ISSUE THREAD

**Issue by ublink** [olympum/waterrower-ble#3]
Not sure if this is intended behavior.  In order to get power data to iPhone, I needed to run two separate services, ie:
node main.js ble
and 
node main.js usb

Can both of these be piped in as 'node main.js usb ble'?  Was going to try modifying main.js to test.

**Comment by olympum** [comment]
just write `node main.js` and that will start both the ble and ant+ implementation. the USB connector was for multicasting over the local network.
